import type { Lang } from "./types";

const en = {
  title: "Breez live",
  warn: "Regtest is play money. Mainnet moves real bitcoin. The seed stays on this device.",
  connected: "Connected",
  offline: "Not connected",
  seed: "Live seed",
  show: "Show",
  hide: "Hide",
  copy: "Copy",
  newSeed: "New seed",
  network: "Network",
  account: "Account",
  connect: "Connect",
  disconnect: "Disconnect",
  working: "Working…",
  result: "Result",
  send: "Send",
  receive: "Receive",
  lnurl: "LNURL",
  address: "Lightning address",
  buy: "Buy and Cash App",
  deposits: "Deposits",
  tokens: "Tokens",
  contacts: "Contacts",
  fiat: "Fiat",
  settings: "SDK settings",
  advanced: "Advanced",
  wallet: "Wallet",
  destination: "To",
  amount: "Amount",
  tokenId: "Token id",
  prepare: "Prepare",
  pay: "Pay",
  unsigned: "Unsigned package",
  speed: "On-chain speed",
  description: "Description",
  method: "Request",
  routes: "Load routes",
  pick: "Route index",
  username: "Username",
  comment: "Comment",
  parse: "Parse",
  withdraw: "Withdraw",
  auth: "LNURL-auth",
  check: "Check",
  register: "Register",
  current: "Current address",
  remove: "Delete address",
  cash: "Cash App link",
  moon: "MoonPay",
  link: "Payment link",
  txid: "Transaction",
  vout: "Output",
  quote: "Quote",
  claim: "Claim",
  refund: "Refund",
  dest: "Refund address",
  fee: "Fee rate",
  name: "Name",
  ticker: "Ticker",
  decimals: "Decimals",
  supply: "Max supply",
  freeze: "Freezable",
  create: "Create token",
  mint: "Mint",
  burn: "Burn",
  lock: "Freeze address",
  unlock: "Unfreeze",
  issuer: "Issuer state",
  lookup: "Token metadata",
  add: "Add contact",
  update: "Update contact",
  id: "Id",
  currencies: "Currencies",
  rates: "Rates",
  privateOn: "Private mode on",
  privateOff: "Private mode off",
  stable: "Stable label",
  clearStable: "Clear stable label",
  master: "Watch-only key",
  clearMaster: "Clear watch key",
  read: "Read settings",
  hookUrl: "Webhook URL",
  secret: "Webhook secret",
  hook: "Register webhook",
  hooks: "List webhooks",
  unhook: "Remove webhook",
  status: "Spark status",
  sync: "Sync",
  info: "Balance",
  history: "Payments",
  leaves: "Optimize leaves",
  fees: "Fee rates",
  sign: "Sign message",
  verify: "Check signature",
  message: "Message",
  pubkey: "Pubkey",
  signature: "Signature",
  conversions: "Refund conversions",
  exit: "Prepare exit",
  exportExit: "Export exit",
  broadcast: "Broadcast exit",
  checkExit: "Check exit",
  importExit: "Import exit",
  turnkey: "Turnkey",
  org: "Organization",
  walletId: "Wallet id",
  batch: "Batch pay",
  htlc: "Claim HTLC",
  limits: "Conversion limits",
  authorize: "Authorize address",
  claimAddr: "Claim address",
  balance: "Balance",
  keyMissing: "Save a Breez API key in Settings before mainnet.",
  badSeed: "That is not a 12 or 24 word seed.",
};

const bn: Record<keyof typeof en, string> = {
  title: "Breez লাইভ",
  warn: "Regtest খেলার টাকা। Mainnet-এ আসল বিটকয়েন যায়। সিড এই ডিভাইসে থাকে।",
  connected: "কানেক্টেড",
  offline: "কানেক্ট নেই",
  seed: "লাইভ সিড",
  show: "দেখান",
  hide: "লুকান",
  copy: "কপি",
  newSeed: "নতুন সিড",
  network: "নেটওয়ার্ক",
  account: "অ্যাকাউন্ট",
  connect: "কানেক্ট",
  disconnect: "ডিসকানেক্ট",
  working: "কাজ চলছে…",
  result: "রেজাল্ট",
  send: "পাঠান",
  receive: "নিন",
  lnurl: "LNURL",
  address: "লাইটনিং ঠিকানা",
  buy: "কেনা ও ক্যাশ অ্যাপ",
  deposits: "ডিপোজিট",
  tokens: "টোকেন",
  contacts: "কন্টাক্ট",
  fiat: "ফিয়াট",
  settings: "SDK সেটিংস",
  advanced: "অ্যাডভান্সড",
  wallet: "ওয়ালেট",
  destination: "যাকে",
  amount: "অ্যামাউন্ট",
  tokenId: "টোকেন আইডি",
  prepare: "প্রিপেয়ার",
  pay: "পে",
  unsigned: "আনসাইনড প্যাকেজ",
  speed: "অন-চেইন স্পিড",
  description: "বর্ণনা",
  method: "রিকোয়েস্ট",
  routes: "রুট আনুন",
  pick: "রুট নম্বর",
  username: "ইউজারনেম",
  comment: "কমেন্ট",
  parse: "পড়ুন",
  withdraw: "উইথড্র",
  auth: "LNURL-auth",
  check: "চেক",
  register: "রেজিস্টার",
  current: "বর্তমান ঠিকানা",
  remove: "ঠিকানা মুছুন",
  cash: "ক্যাশ অ্যাপ লিংক",
  moon: "MoonPay",
  link: "পেমেন্ট লিংক",
  txid: "ট্রানজ্যাকশন",
  vout: "আউটপুট",
  quote: "কোট",
  claim: "ক্লেইম",
  refund: "রিফান্ড",
  dest: "রিফান্ড ঠিকানা",
  fee: "ফি রেট",
  name: "নাম",
  ticker: "টিকার",
  decimals: "ডেসিমাল",
  supply: "সর্বোচ্চ সাপ্লাই",
  freeze: "ফ্রিজ করা যাবে",
  create: "টোকেন তৈরি",
  mint: "মিন্ট",
  burn: "বার্ন",
  lock: "ঠিকানা ফ্রিজ",
  unlock: "আনফ্রিজ",
  issuer: "ইস্যুয়ার স্টেট",
  lookup: "টোকেন মেটাডেটা",
  add: "কন্টাক্ট যোগ",
  update: "কন্টাক্ট বদলান",
  id: "আইডি",
  currencies: "কারেন্সি",
  rates: "রেট",
  privateOn: "প্রাইভেট মোড অন",
  privateOff: "প্রাইভেট মোড অফ",
  stable: "স্টেবল লেবেল",
  clearStable: "স্টেবল লেবেল সরান",
  master: "ওয়াচ-অনলি কি",
  clearMaster: "ওয়াচ কি সরান",
  read: "সেটিংস পড়ুন",
  hookUrl: "ওয়েবহুক URL",
  secret: "ওয়েবহুক সিক্রেট",
  hook: "ওয়েবহুক যোগ",
  hooks: "ওয়েবহুক তালিকা",
  unhook: "ওয়েবহুক সরান",
  status: "স্পার্ক স্ট্যাটাস",
  sync: "সিঙ্ক",
  info: "ব্যালেন্স",
  history: "পেমেন্ট",
  leaves: "লিফ অপটিমাইজ",
  fees: "ফি রেট",
  sign: "মেসেজ সাইন",
  verify: "সিগনেচার চেক",
  message: "মেসেজ",
  pubkey: "পাবকি",
  signature: "সিগনেচার",
  conversions: "কনভার্সন রিফান্ড",
  exit: "এক্সিট প্রিপেয়ার",
  exportExit: "এক্সিট এক্সপোর্ট",
  broadcast: "এক্সিট ব্রডকাস্ট",
  checkExit: "এক্সিট চেক",
  importExit: "এক্সিট ইমপোর্ট",
  turnkey: "Turnkey",
  org: "অর্গানাইজেশন",
  walletId: "ওয়ালেট আইডি",
  batch: "ব্যাচ পে",
  htlc: "HTLC ক্লেইম",
  limits: "কনভার্সন লিমিট",
  authorize: "ঠিকানা অথরাইজ",
  claimAddr: "ঠিকানা ক্লেইম",
  balance: "ব্যালেন্স",
  keyMissing: "Mainnet-এর আগে সেটিংসে Breez API key সেভ করুন।",
  badSeed: "এটা ১২ বা ২৪ শব্দের সিড না।",
};

export type SdkCopy = keyof typeof en;

export function sdkText(lang: Lang, key: SdkCopy) {
  return lang === "bn" ? bn[key] : en[key];
}
